-- =========================================
-- UniWell Database Schema (Supabase client architecture)
-- Run once in the Supabase SQL Editor on an empty project.
--
-- Architecture: the React app talks to Supabase directly via supabase-js.
-- Auth lives in Supabase Auth (auth.users, UUIDs). App data lives in public.*
-- and is protected by RLS — no Express server in the middle.
-- =========================================

-- ── Enum types ───────────────────────────────────────────────────────────────
do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type public.user_role as enum ('student', 'admin');
  end if;
  if not exists (select 1 from pg_type where typname = 'mood_type') then
    create type public.mood_type as enum ('rad', 'good', 'meh', 'bad', 'awful');
  end if;
  if not exists (select 1 from pg_type where typname = 'trigger_category') then
    create type public.trigger_category as enum (
      'Academics', 'Social', 'Family', 'Health',
      'Finance', 'Relationships', 'Personal Growth', 'Other'
    );
  end if;
  if not exists (select 1 from pg_type where typname = 'coping_category') then
    create type public.coping_category as enum (
      'Relaxation', 'Time Management', 'Social Support',
      'Physical Activity', 'Creative Expression', 'Mindfulness', 'Other'
    );
  end if;
  if not exists (select 1 from pg_type where typname = 'coping_status') then
    create type public.coping_status as enum ('pending', 'approved', 'rejected');
  end if;
end$$;

-- ── Profiles (1:1 with auth.users) ───────────────────────────────────────────
create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  name        varchar(150) not null,
  student_id  varchar(50)  not null unique,
  course      varchar(100) not null,
  year_level  smallint     not null check (year_level between 1 and 4),
  role        public.user_role not null default 'student',
  created_at  timestamptz  not null default now()
);

create index if not exists profiles_role_idx on public.profiles (role);

-- Auto-create a profile when an auth user is created, reading metadata supplied
-- at sign-up time via options.data.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, student_id, course, year_level, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'student_id', new.id::text),
    coalesce(new.raw_user_meta_data ->> 'course', 'Unspecified'),
    coalesce((new.raw_user_meta_data ->> 'year_level')::smallint, 1),
    coalesce((new.raw_user_meta_data ->> 'role')::public.user_role, 'student')
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Convenience: is_admin() helper for RLS policies.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;

grant execute on function public.is_admin() to authenticated;

-- ── Mood logs ────────────────────────────────────────────────────────────────
create table if not exists public.mood_logs (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references public.profiles(id) on delete cascade,
  mood_type  public.mood_type not null,
  intensity  smallint not null default 3 check (intensity between 1 and 5),
  note       text,
  logged_at  timestamptz not null default now()
);

create index if not exists mood_logs_user_logged_at_idx
  on public.mood_logs (user_id, logged_at desc);

-- ── Mood triggers ────────────────────────────────────────────────────────────
create table if not exists public.mood_triggers (
  id               bigint generated by default as identity primary key,
  log_id           bigint not null references public.mood_logs(id) on delete cascade,
  trigger_category public.trigger_category not null
);

create index if not exists mood_triggers_log_id_idx on public.mood_triggers (log_id);

-- ── Journal entries ──────────────────────────────────────────────────────────
create table if not exists public.journal_entries (
  id         bigint generated by default as identity primary key,
  user_id    uuid not null references public.profiles(id) on delete cascade,
  content    text not null,
  prompt     text,
  created_at timestamptz not null default now()
);

create index if not exists journal_entries_user_created_at_idx
  on public.journal_entries (user_id, created_at desc);

-- ── Coping strategies ────────────────────────────────────────────────────────
create table if not exists public.coping_strategies (
  id            bigint generated by default as identity primary key,
  submitter_id  uuid not null references public.profiles(id) on delete cascade,
  category      public.coping_category not null,
  title         varchar(200) not null,
  description   text not null,
  trigger_tags  jsonb not null default '[]'::jsonb,
  status        public.coping_status not null default 'pending',
  helpful_count integer not null default 0,
  created_at    timestamptz not null default now()
);

create index if not exists coping_strategies_feed_idx
  on public.coping_strategies (status, helpful_count desc, created_at desc);

create index if not exists coping_strategies_trigger_tags_idx
  on public.coping_strategies using gin (trigger_tags);

-- ── Helpful votes ────────────────────────────────────────────────────────────
create table if not exists public.helpful_votes (
  id          bigint generated by default as identity primary key,
  strategy_id bigint not null references public.coping_strategies(id) on delete cascade,
  user_id     uuid not null references public.profiles(id) on delete cascade,
  voted_at    timestamptz not null default now(),
  constraint helpful_votes_strategy_user_unique unique (strategy_id, user_id)
);

-- ── RLS ──────────────────────────────────────────────────────────────────────
alter table public.profiles          enable row level security;
alter table public.mood_logs         enable row level security;
alter table public.mood_triggers     enable row level security;
alter table public.journal_entries   enable row level security;
alter table public.coping_strategies enable row level security;
alter table public.helpful_votes     enable row level security;

-- Grants — RLS is the gate, so grant CRUD then restrict via policies.
grant usage on schema public to anon, authenticated;
grant select on public.profiles          to authenticated;
grant select, insert, update, delete on public.mood_logs         to authenticated;
grant select, insert, update, delete on public.mood_triggers     to authenticated;
grant select, insert, update, delete on public.journal_entries   to authenticated;
grant select, insert, update, delete on public.coping_strategies to authenticated;
grant select, insert,        delete on public.helpful_votes      to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- profiles: read own + anyone can read displayed names for approved coping;
-- admins can read all; updates via functions/triggers only.
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.is_admin() or role = 'student');

drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles
  for update to authenticated
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());

-- mood_logs: student owns their rows; admin reads all.
drop policy if exists mood_logs_select on public.mood_logs;
create policy mood_logs_select on public.mood_logs
  for select to authenticated
  using (user_id = auth.uid() or public.is_admin());

drop policy if exists mood_logs_insert on public.mood_logs;
create policy mood_logs_insert on public.mood_logs
  for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists mood_logs_delete on public.mood_logs;
create policy mood_logs_delete on public.mood_logs
  for delete to authenticated
  using (user_id = auth.uid());

-- mood_triggers: follow parent log's ownership.
drop policy if exists mood_triggers_select on public.mood_triggers;
create policy mood_triggers_select on public.mood_triggers
  for select to authenticated
  using (
    exists (
      select 1 from public.mood_logs ml
      where ml.id = mood_triggers.log_id
        and (ml.user_id = auth.uid() or public.is_admin())
    )
  );

drop policy if exists mood_triggers_insert on public.mood_triggers;
create policy mood_triggers_insert on public.mood_triggers
  for insert to authenticated
  with check (
    exists (
      select 1 from public.mood_logs ml
      where ml.id = mood_triggers.log_id and ml.user_id = auth.uid()
    )
  );

-- journal_entries: purely private; admin does NOT get read access.
drop policy if exists journal_select_own on public.journal_entries;
create policy journal_select_own on public.journal_entries
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists journal_insert_own on public.journal_entries;
create policy journal_insert_own on public.journal_entries
  for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists journal_delete_own on public.journal_entries;
create policy journal_delete_own on public.journal_entries
  for delete to authenticated
  using (user_id = auth.uid());

-- coping_strategies: approved visible to all authenticated; own + admin see pending/rejected.
drop policy if exists coping_select on public.coping_strategies;
create policy coping_select on public.coping_strategies
  for select to authenticated
  using (
    status = 'approved'
    or submitter_id = auth.uid()
    or public.is_admin()
  );

drop policy if exists coping_insert_own on public.coping_strategies;
create policy coping_insert_own on public.coping_strategies
  for insert to authenticated
  with check (submitter_id = auth.uid() and status = 'pending');

-- Admin moderation: only admins can flip status.
drop policy if exists coping_update_admin on public.coping_strategies;
create policy coping_update_admin on public.coping_strategies
  for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- helpful_votes: student owns their own votes.
drop policy if exists helpful_votes_select_own on public.helpful_votes;
create policy helpful_votes_select_own on public.helpful_votes
  for select to authenticated
  using (user_id = auth.uid());

drop policy if exists helpful_votes_insert_own on public.helpful_votes;
create policy helpful_votes_insert_own on public.helpful_votes
  for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists helpful_votes_delete_own on public.helpful_votes;
create policy helpful_votes_delete_own on public.helpful_votes
  for delete to authenticated
  using (user_id = auth.uid());

-- ── RPCs ─────────────────────────────────────────────────────────────────────

-- Log a mood + triggers atomically.
create or replace function public.log_mood(
  p_mood_type public.mood_type,
  p_intensity smallint,
  p_note text,
  p_triggers public.trigger_category[]
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_log_id bigint;
begin
  insert into public.mood_logs (user_id, mood_type, intensity, note)
  values (auth.uid(), p_mood_type, p_intensity, p_note)
  returning id into v_log_id;

  if p_triggers is not null and array_length(p_triggers, 1) > 0 then
    insert into public.mood_triggers (log_id, trigger_category)
    select v_log_id, t from unnest(p_triggers) as t;
  end if;

  return v_log_id;
end;
$$;

grant execute on function public.log_mood(public.mood_type, smallint, text, public.trigger_category[])
  to authenticated;

-- Toggle a helpful vote + keep helpful_count in sync.
create or replace function public.toggle_helpful_vote(p_strategy_id bigint)
returns boolean
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_exists boolean;
begin
  select exists(
    select 1 from public.helpful_votes
    where strategy_id = p_strategy_id and user_id = v_uid
  ) into v_exists;

  if v_exists then
    delete from public.helpful_votes
      where strategy_id = p_strategy_id and user_id = v_uid;
    update public.coping_strategies
      set helpful_count = greatest(0, helpful_count - 1)
      where id = p_strategy_id;
    return false;
  else
    insert into public.helpful_votes (strategy_id, user_id)
    values (p_strategy_id, v_uid);
    update public.coping_strategies
      set helpful_count = helpful_count + 1
      where id = p_strategy_id;
    return true;
  end if;
end;
$$;

grant execute on function public.toggle_helpful_vote(bigint) to authenticated;

-- Admin analytics aggregate. SECURITY DEFINER so it can scan all users
-- while still gating via is_admin() check.
create or replace function public.admin_analytics(
  p_days integer default 30,
  p_year_level integer default null,
  p_course text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_since timestamptz := now() - (p_days * interval '1 day');
  v_result jsonb;
begin
  if not public.is_admin() then
    raise exception 'forbidden' using errcode = '42501';
  end if;

  with base as (
    select ml.*, p.year_level, p.course
    from public.mood_logs ml
    join public.profiles p on p.id = ml.user_id
    where ml.logged_at >= v_since
      and (p_year_level is null or p.year_level = p_year_level)
      and (p_course is null or p.course = p_course)
  )
  select jsonb_build_object(
    'totalStudents', (select count(distinct user_id)::int from base),
    'moodDistribution', coalesce((
      select jsonb_agg(x) from (
        select mood_type, count(*)::int as count
        from base group by mood_type
      ) x
    ), '[]'::jsonb),
    'dailyTrend', coalesce((
      select jsonb_agg(x order by x->>'date') from (
        select jsonb_build_object(
          'date', (logged_at at time zone 'UTC')::date,
          'mood_type', mood_type,
          'count', count(*)::int
        ) as x
        from base
        group by (logged_at at time zone 'UTC')::date, mood_type
      ) y
    ), '[]'::jsonb),
    'topTriggers', coalesce((
      select jsonb_agg(x order by (x->>'count')::int desc) from (
        select jsonb_build_object(
          'trigger_category', mt.trigger_category,
          'count', count(*)::int
        ) as x
        from public.mood_triggers mt
        join base on base.id = mt.log_id
        group by mt.trigger_category
      ) y
    ), '[]'::jsonb),
    'byYearLevel', coalesce((
      select jsonb_agg(x order by (x->>'year_level')::int) from (
        select jsonb_build_object(
          'year_level', year_level,
          'mood_type', mood_type,
          'count', count(*)::int
        ) as x
        from base group by year_level, mood_type
      ) y
    ), '[]'::jsonb),
    'byCourse', coalesce((
      select jsonb_agg(x order by x->>'course') from (
        select jsonb_build_object(
          'course', course,
          'mood_type', mood_type,
          'count', count(*)::int
        ) as x
        from base group by course, mood_type
      ) y
    ), '[]'::jsonb)
  ) into v_result;

  return v_result;
end;
$$;

grant execute on function public.admin_analytics(integer, integer, text) to authenticated;

-- ── Bootstrap notes ──────────────────────────────────────────────────────────
-- 1. Create your admin account in the Supabase dashboard:
--      Authentication -> Users -> "Add user" (email + password, "Auto Confirm User" ON).
-- 2. Then fill in the profile row and flip the role:
--      update public.profiles
--         set name = 'Guidance Admin', student_id = 'ADMIN-001',
--             course = 'Administration', year_level = 1, role = 'admin'
--       where id = (select id from auth.users where email = 'admin@uniwell.edu.ph');
--    (The row was created automatically by handle_new_user; you're just
--     filling in fields that were defaulted.)
